### PR TITLE
Favorite

### PR DESCRIPTION
**Pull request by TeriPastorino**
@cbeck 
have some weird scope error at onset of this section that i don't understand/not sure how to begin to solve
will spend tonight trying to do some research on it, but so tired of feeling so lost and behind. so i just plowed through this checkpoint for the sake of getting it done

per emails - couldn't test rspec stuff due to weird errors, and could test the favoriting due to scope error

please review and we can discuss tomorrow am. if there are any changes i can make before then send me a note

thanks
t

### CODE REVIEW

**Comment by cbeck** [comment]
Not sure what your 'scope' error is - can you send me the stack trace?

**Comment by TeriPastorino** [comment]
i think i sent it through the bloc messages or tied to the questions section of that checkpoint 

i will double check 

----- Original Message -----

**Comment by TeriPastorino** [comment]
oh no error now 
must be due to merge and outstanding stuff 

woohoo 

----- Original Message -----

**Comment by TeriPastorino** [comment]
I just submitted in the questions part of the favorite checkpoint 

just got it again - switched to favorite branch and selected a post hoping to see the work from favorite and it happened again 

----- Original Message -----

**Pull request merged**
